# Setup meeting


## Date & location:


## Present:


## Agenda:

@. Collaborative  tools:

	- [GitHub](https://github.com)
		- Central project repo on the NBISweden GitHub organization
		- Code versioning, logbook, meeting notes, etc.
	- [Confluence](https://scilifelab.atlassian.net)
		- Private Wiki for viewing rendered logbook files, meeting minutes, etc.

@. Critical raw data:

	1. Keep an inventory of important data and make a plan for how it should be treated. Inform collaborators of this plan.
	2. Make sure you keep a separate local copy of crucial data.
	3. Also put important data in a backed up remote directory (and nothing else, so that the backup system does not get bogged down).
	4. Run `chmod -R -w .` in that directory. This command makes the directory and all contents read-only, so you can't easily overwrite or change it. This is not a substitute for a secondary backup!
	5. Info on data backups on the clusters:
		- Rackham (Crex storage): 30-day incremental back-up, and not all folders are backed up, [read more](https://www.uppmax.uu.se/support/faq/resources-faq/backup-at-uppmax).
		- Dardel (Klemming storage): no back up except 25 GB in the home directory, [read more](https://www.pdc.kth.se/support/documents/data_management/klemming.html).
	6. Archive raw data in external repositories (ENA/SRA) sooner rather than later - this can often be kept under embargo.

@. Review of [previous actions](YYYYMMDD-01_kickoff.qmd#actions)

	- What's been done so far?

@. Next project steps

## Actions:

1. Action, Name, Due Date

## Next meeting:

